(()=>{'use strict';
 const base=new URL('.',document.currentScript.src),asset=n=>new URL('assets/'+n,base).href,cv=new URL('Chen_Zihua_CV.docx',base).href;
 const cases=[
 {id:'xhs',title:{en:'Xiaohongshu',zh:'小紅書內容與營運'},summary:{en:'Content shaped around what people search for, save and share. I lead planning and production, with hands-on work across topics, scripts, shooting, editing and copy.',zh:'從受眾洞察與選題出發，主導內容策劃及製作，親自參與腳本、拍攝、剪輯和文案，並負責審稿、發布與覆盤。'},image:asset('work-xhs.png'),metric:'1M+',scope:{en:'Views on one Xiaohongshu post. 500+ content pieces across multiple platforms overall.',zh:'小紅書單篇內容瀏覽；跨平台累計負責 500+ 篇內容。'},steps:{en:['Research audience interests and useful search topics.','Translate the idea into a shootable script and visual direction.','Produce, review and publish the content.','Review weekly performance and refine the next round.'],zh:['研究受眾興趣、搜尋需求與內容趨勢。','將選題轉化為腳本與具體視覺方向。','製作、審稿並安排發布。','每週分析表現，調整下一輪內容。']}},
 {id:'creators',title:{en:'Creator partnerships',zh:'內地及海外達人合作'},summary:{en:'I lead creator collaboration from selection and briefing to shoots, review and reporting. Xiaohongshu is my strongest area, alongside overseas creator work on Instagram and YouTube.',zh:'主導創作者篩選、商務洽談、合作簡報、拍攝、審核及成效覆盤。以小紅書合作為重點，並具備 Instagram、YouTube 海外達人合作經驗。'},image:asset('work-creators.png'),metric:'1,000+',scope:{en:'Creator and food-blogger collaboration occasions overall; not a count of unique creators or Xiaohongshu-only collaborations.',zh:'整體達人及美食博主合作次數，並非獨立達人人數或小紅書單平台總量。'},steps:{en:['Select creators for audience and brand fit.','Agree deliverables, quotations and a clear creative brief.','Coordinate shoots, publication and content review.','Use results to inform future creator choices.'],zh:['按受眾與品牌需求篩選創作者。','洽談報價、內容要求與合作簡報。','跟進拍攝、內容審核及發布安排。','根據成效調整後續合作選擇。']}},
 {id:'content',title:{en:'Content performance',zh:'內容製作與成效'},summary:{en:'Ideas need follow-through. I connect visual content, creator work and campaign delivery, then review content performance and activity sales to guide the next decision.',zh:'把內容創意、達人合作及活動執行連接起來，透過內容表現與活動銷售數據覆盤，調整選題、資源及推廣方向。'},image:asset('work-content.png'),metric:'500+',scope:{en:'Content pieces across platforms. Conversion capability is shown through the work process; attributable conversion figures will be added when available.',zh:'跨平台內容累計；先展示內容及轉化思路，可歸因的具體轉化數據後續補充。'},steps:{en:['Define the audience and the intended consumer action.','Create visual content and copy suited to each platform.','Connect publishing with launches, retail and offline activity.','Review results and apply the findings to future work.'],zh:['明確受眾與希望促成的消費者行動。','按不同平台製作圖文、短片與文案。','配合新品、門店及線下活動安排發布。','分析結果並落實到後續推廣。']}}
 ];
 let lang='en',enabled=!matchMedia('(prefers-reduced-motion:reduce)').matches;const reduce=matchMedia('(prefers-reduced-motion:reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)'),listeners=new Set();let raf=0,last=0,hidden=document.hidden;const pointer={x:innerWidth/2,y:innerHeight/2,nx:0,ny:0,live:false},ring={x:pointer.x,y:pointer.y};
 const cursor=document.createElement('div');cursor.className='demo-cursor';cursor.setAttribute('aria-hidden','true');document.body.append(cursor);
 const dialog=document.createElement('dialog');dialog.className='demo-dialog';dialog.setAttribute('aria-label','Selected work');document.body.append(dialog);let returnFocus=null,dialogCase=null,isAbout=false;
 const txt=o=>o[lang],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function renderDialog(){let heading,content;if(isAbout){heading=lang==='zh'?'關於陳姿華':'About Chen Zihua';content=`<div class="demo-about"><h2>${lang==='zh'?'主導策劃，親自落地。':'Ideas led. Work made.'}</h2><p>${lang==='zh'?'具備逾兩年香港餐飲及消費品牌營銷經驗，現於恆香主導三個品牌的日常市場推廣。專注小紅書內容與達人合作，同時熟悉 Instagram、Facebook 等平台。':'A Hong Kong marketing professional with over two years in F&B and consumer brands. At Hang Heung, I lead day-to-day marketing across three brands, with a focus on Xiaohongshu content and creator partnerships.'}</p><p>${lang==='zh'?'從選題、腳本、拍攝剪輯及合作洽談，到活動執行、預算跟進與成效覆盤，均具備實務經驗。':'My work spans planning, scripting, filming, editing and copy, through to creator briefings, campaign delivery, budget follow-up and performance review.'}</p><p>${lang==='zh'?'香港城市大學 市場營銷碩士 · 悉尼大學 商學學士':'Master of Marketing, City University of Hong Kong · Bachelor of Commerce, University of Sydney'}</p><a href="${cv}" download>${lang==='zh'?'下載履歷':'Download CV'} ↗</a><a href="mailto:zche2476@gmail.com">zche2476@gmail.com ↗</a></div>`;}else{const c=cases.find(c=>c.id===dialogCase);heading=txt(c.title);content=`<div class="demo-case-layout"><div><img class="demo-case-image" src="${c.image}" alt="${lang==='zh'?'抽象作品視覺示意':'Conceptual work-cover visual study'}"><p class="demo-case-study-note">${lang==='zh'?'封面為視覺示意，實際作品素材待補。':'Cover is a visual study; actual project assets to follow.'}</p></div><div class="demo-case-body"><h2>${esc(heading)}</h2><p>${esc(txt(c.summary))}</p><strong class="demo-case-metric">${c.metric}</strong><div class="demo-case-scope">${esc(txt(c.scope))}</div><h3>${lang==='zh'?'我如何推進':'How I carry the work through'}</h3><ol>${c.steps[lang].map(s=>`<li>${esc(s)}</li>`).join('')}</ol><a href="mailto:zche2476@gmail.com">${lang==='zh'?'聯絡我':'Get in touch'} ↗</a></div></div>`;}dialog.innerHTML=`<div class="demo-dialog-head"><span>${esc(heading)}</span><button class="demo-dialog-close" aria-label="${lang==='zh'?'關閉':'Close'}">×</button></div>${content}`;dialog.querySelector('.demo-dialog-close').addEventListener('click',()=>dialog.close());}
 function show(id){cursor.style.opacity='0';document.documentElement.classList.remove('demo-pointer');dialogCase=id;isAbout=!id;returnFocus=document.activeElement;renderDialog();dialog.showModal();document.body.dataset.caseOpen=id||'about';}
 dialog.addEventListener('close',()=>{delete document.body.dataset.caseOpen;returnFocus?.focus?.();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 let ctx=null,master=null,audioWanted=false,musicTimer=null,musicStep=0;const notes=[48,55,60,64,62,55,59,67,52,59,64,67,62,57,60,64];
 function playTone(midi,at,len,volume){const frequency=440*2**((midi-69)/12);const gain=ctx.createGain();gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(volume,at+.04);gain.gain.exponentialRampToValueAtTime(.00005,at+len);gain.connect(master);for(const [ratio,weight] of [[1,1],[2,.14],[3,.025]]){const osc=ctx.createOscillator(),g=ctx.createGain();osc.type='sine';osc.frequency.value=frequency*ratio;g.gain.value=weight;osc.connect(g);g.connect(gain);osc.start(at);osc.stop(at+len+.1);}}
 function music(){if(!audioWanted||hidden||!ctx)return;const at=ctx.currentTime+.04;playTone(notes[musicStep%notes.length],at,5,.037);if(musicStep%4===0)playTone(notes[musicStep%notes.length]-12,at,8,.018);musicStep++;}
 async function setSound(on){audioWanted=on;clearInterval(musicTimer);musicTimer=null;try{if(on){ctx??=new (window.AudioContext||window.webkitAudioContext)();if(!master){master=ctx.createGain();master.gain.value=.55;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=2600;master.connect(filter);filter.connect(ctx.destination);}if(!hidden){await ctx.resume();music();musicTimer=setInterval(music,1900);}}else if(ctx)await ctx.suspend();}catch{audioWanted=false;}document.body.dataset.sound=audioWanted?'on':'off';document.body.dataset.audioState=ctx?.state||'off';updateControls();}
 function updateControls(){document.querySelectorAll('[data-action="sound"]').forEach(b=>{(b.querySelector('[data-control-label]')||b).textContent=lang==='zh'?(audioWanted?'聲音開啟':'聲音關閉'):(audioWanted?'Sound on':'Sound off');b.setAttribute('aria-pressed',String(audioWanted));b.dataset.state=audioWanted?'on':'off';});document.querySelectorAll('[data-action="motion"]').forEach(b=>{(b.querySelector('[data-control-label]')||b).textContent=lang==='zh'?(enabled?'動效開啟':'動效關閉'):(enabled?'Motion on':'Motion off');b.setAttribute('aria-pressed',String(enabled));b.dataset.state=enabled?'on':'off';});document.querySelectorAll('[data-action="lang"]').forEach(b=>{b.setAttribute('aria-label',lang==='en'?'Switch to Traditional Chinese':'切換至英文');b.dataset.lang=lang;});}
 function translate(){document.documentElement.lang=lang==='en'?'en':'zh-Hant';document.querySelectorAll('[data-en][data-zh]').forEach(el=>el.textContent=el.dataset[lang]);updateControls();if(dialog.open)renderDialog();dispatchEvent(new CustomEvent('demo:language',{detail:{lang}}));}
 function setMotion(value){enabled=value&&!reduce.matches;document.body.classList.toggle('demo-motion-off',!enabled);document.body.dataset.motion=enabled?'on':'off';if(!enabled){cursor.style.opacity='0';document.documentElement.classList.remove('demo-pointer');}updateControls();dispatchEvent(new CustomEvent('demo:motion',{detail:{enabled}}));schedule();}
 function schedule(){if(!raf&&!hidden)raf=requestAnimationFrame(tick);}function tick(time){raf=0;if(hidden)return;const dt=Math.min(.04,Math.max(.001,(time-last)/1000||1/60));last=time;if(enabled&&fine.matches&&pointer.live){const k=1-Math.exp(-15*dt);ring.x+=(pointer.x-ring.x)*k;ring.y+=(pointer.y-ring.y)*k;cursor.style.transform=`translate(${ring.x}px,${ring.y}px)`;}const state={time,dt,pointer,width:innerWidth,height:innerHeight,enabled};for(const fn of listeners)fn(state);if(enabled)schedule();}
 window.PortfolioDemo={cases,get lang(){return lang;},get enabled(){return enabled;},openCase:id=>show(id),onFrame(fn){listeners.add(fn);schedule();return()=>listeners.delete(fn);},setLanguage(value){lang=value==='zh'?'zh':'en';translate();},setMotion};
 document.addEventListener('click',e=>{const open=e.target.closest('[data-open-case]');if(open){e.preventDefault();show(open.dataset.openCase);return;}const b=e.target.closest('[data-action]');if(!b)return;switch(b.dataset.action){case'lang':lang=lang==='en'?'zh':'en';translate();break;case'sound':setSound(!audioWanted);break;case'motion':setMotion(!enabled);break;case'about':case'contact':show(null);break;}});
 addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;pointer.nx=e.clientX/innerWidth*2-1;pointer.ny=e.clientY/innerHeight*2-1;pointer.live=true;if(enabled&&fine.matches&&e.pointerType!=='touch'&&!dialog.open){cursor.style.opacity='1';document.documentElement.classList.add('demo-pointer');const target=e.target.closest('a,button');cursor.classList.toggle('is-link',!!target);cursor.textContent=target?.dataset.cursor||'';}schedule();},{passive:true});document.addEventListener('pointerout',e=>{if(!e.relatedTarget){pointer.live=false;cursor.style.opacity='0';document.documentElement.classList.remove('demo-pointer');}});
 document.addEventListener('visibilitychange',()=>{hidden=document.hidden;if(hidden){cancelAnimationFrame(raf);raf=0;clearInterval(musicTimer);musicTimer=null;if(ctx)ctx.suspend();}else{last=0;schedule();if(audioWanted)setSound(true);}});addEventListener('resize',schedule);addEventListener('scroll',schedule,{passive:true});reduce.addEventListener('change',()=>setMotion(!reduce.matches));setMotion(enabled);translate();
})();


